/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaConsultas;

import Dominio.*;

/**
 *
 * @author Luciano Umpierrez 
 */
public class AreaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form AreaConsulta
     */
    public AreaConsulta(RegistrarDueño unRegistroDueño, RegistroPuesto unRegistroPuesto,
            RegistroProducto unRegistroProducto, RegistroVenta unRegistroVenta,
            RegistroCompra unRegistroCompra, RegistroMayorista unRegistroMayorista) {
        initComponents();
        this.setTitle("Área de consultas");
        this.registroDueño = unRegistroDueño;
        this.registroPuesto = unRegistroPuesto;
        this.registroCompras = unRegistroCompra;
        this.registroVentas = unRegistroVenta;
        this.registroProductos = unRegistroProducto;
        this.registroMayoristas = unRegistroMayorista;
        this.consultaDueño = new ConsultaDueño(registroDueño);
        this.consultaPuesto = new ConsultaPuesto(registroPuesto);
         this.generarArchivo = new GenerarArchivo(registroCompras, registroVentas, registroPuesto);
        this.consultaProducto = new ConsultaProducto(registroCompras, registroProductos,
                registroVentas);
        this.consultaMayorista = new ConsultaMayorista(registroMayoristas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDueños = new javax.swing.JButton();
        btnConsultaPuesto = new javax.swing.JButton();
        btnConsProducto = new javax.swing.JButton();
        btnConsMayo = new javax.swing.JButton();
        btnGenArch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnDueños.setText("Consultar dueño");
        btnDueños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDueñosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDueños);
        btnDueños.setBounds(120, 40, 150, 23);

        btnConsultaPuesto.setText("Consultar Puesto");
        btnConsultaPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaPuestoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaPuesto);
        btnConsultaPuesto.setBounds(120, 90, 150, 23);

        btnConsProducto.setText("Consultar producto");
        btnConsProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsProducto);
        btnConsProducto.setBounds(120, 140, 150, 23);

        btnConsMayo.setText("Consultar mayorista");
        btnConsMayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsMayoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsMayo);
        btnConsMayo.setBounds(120, 190, 150, 23);

        btnGenArch.setText("Generar archivo");
        btnGenArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenArchActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenArch);
        btnGenArch.setBounds(120, 240, 150, 23);

        setSize(new java.awt.Dimension(412, 344));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDueñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDueñosActionPerformed
        this.consultaDueño.crearTablaDueños();
        this.consultaDueño.setVisible(true);
    }//GEN-LAST:event_btnDueñosActionPerformed

    private void btnConsultaPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaPuestoActionPerformed
        this.consultaPuesto.crearTablaPuestos();
        this.consultaPuesto.setVisible(true);
    }//GEN-LAST:event_btnConsultaPuestoActionPerformed

    private void btnConsProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsProductoActionPerformed
        // TODO add your handling code here:
        this.consultaProducto.mostrarProducto();
        this.consultaProducto.setVisible(true);
    }//GEN-LAST:event_btnConsProductoActionPerformed

    private void btnConsMayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsMayoActionPerformed
        // TODO add your handling code here:
        this.consultaMayorista.setVisible(true);
        this.consultaMayorista.ObjetoAPantalla();
    }//GEN-LAST:event_btnConsMayoActionPerformed

    private void btnGenArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenArchActionPerformed
        this.generarArchivo.ObjetoaPantalla();
        this.generarArchivo.setVisible(true);
    }//GEN-LAST:event_btnGenArchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsMayo;
    private javax.swing.JButton btnConsProducto;
    private javax.swing.JButton btnConsultaPuesto;
    private javax.swing.JButton btnDueños;
    private javax.swing.JButton btnGenArch;
    // End of variables declaration//GEN-END:variables
    private RegistrarDueño registroDueño;
    private ConsultaDueño consultaDueño;
    private ConsultaPuesto consultaPuesto;
    private RegistroPuesto registroPuesto;
    private RegistroVenta registroVentas;
    private RegistroCompra registroCompras;
    private RegistroProducto registroProductos;
    private RegistroMayorista registroMayoristas;
    private ConsultaProducto consultaProducto;
    private ConsultaMayorista consultaMayorista;
    private GenerarArchivo generarArchivo;
}
