package AreaConsultas;

import Dominio.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import java.util.Observer;
import java.util.Observable;

/**
 *
 * @author Luciano Umpierrez 
 */
public class ConsultaProducto extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ConsultaProducto
     */
    public ConsultaProducto(RegistroCompra unRegistroCompra,
            RegistroProducto unRegistroProducto, RegistroVenta unRegistroVenta) {

        initComponents();
        this.setTitle("Consulta producto");
        this.compras = unRegistroCompra;
        this.ventas = unRegistroVenta;
        // this.productos = unRegistroProducto.getListaProductos();
        this.productos = unRegistroProducto;
        this.indiceActual = 0;
        this.puestoPrecioMaximo = new ArrayList<Puesto>();
        this.puestosPrecioMinimo = new ArrayList<Puesto>();
        this.productos.addObserver(this);
    }

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof RegistroProducto && arg instanceof Producto) {
            mostrarProducto();
        }
    }

    public void mostrarListas() {
        Iterator<Puesto> itMaximo = this.puestoPrecioMaximo.iterator();
        Iterator<Puesto> itMinimo = this.puestosPrecioMinimo.iterator();
        DefaultListModel<Puesto> modeloMinimo = new DefaultListModel<>();
        DefaultListModel<Puesto> modeloMaximo = new DefaultListModel<>();

        while (itMaximo.hasNext()) {
            Puesto puesto = itMaximo.next();
            modeloMaximo.addElement(puesto);
        }

        while (itMinimo.hasNext()) {
            Puesto puesto = itMinimo.next();
            modeloMinimo.addElement(puesto);
        }

        this.lstPrecioMaximo.setModel(modeloMaximo);
        this.lstPrecioMinimo.setModel(modeloMinimo);
    }

    public void mostrarProducto() {
        ArrayList<Producto> listaProductos = this.productos.getListaProductos();
        if (!listaProductos.isEmpty()) {
            Producto unProducto = listaProductos.get(this.indiceActual);
            this.txtNombre.setText(unProducto.getNombre());
            this.txtDescripcion.setText(unProducto.getDescripcion());
            this.txtTipo.setText(unProducto.getTipo());
            this.txtVenta.setText(unProducto.getFormaVenta());
            ImageIcon icon = new ImageIcon(unProducto.getFoto());
            this.lblFoto.setIcon(icon);
            this.totalVendidos = this.ventas.totalVendidoProducto();
            this.totalCompras = this.compras.totalCompradoProducto();
            if (this.totalVendidos.get(unProducto) == null) {
                this.txtTotalVendido.setText("0");
            } else {
                this.txtTotalVendido.setText("" + this.totalVendidos.get(unProducto));
            }
            if (this.totalCompras.get(unProducto) == null) {
                this.txtTotalComprado.setText("0");
            } else {
                this.txtTotalComprado.setText("" + this.totalCompras.get(unProducto));
            }
            this.cantidadComprada = this.compras.cantidadComprada(unProducto);
            this.cantidadVendida = this.ventas.cantidadVendida(unProducto);
            this.txtPrecioMinimo.setText("" + this.cantidadVendida[2]);
            this.txtPrecioMaximo.setText("" + this.cantidadVendida[3]);
            int kiloComprado = this.cantidadComprada[0];
            int unidadComprado = this.cantidadComprada[1];
            int kiloVendido = this.cantidadVendida[0];
            int unidadVendida = this.cantidadVendida[1];
            this.txtCantidadComprado.setText(unidadComprado + "/" + kiloComprado);
            this.txtCantidadVendido.setText(unidadVendida + "/" + kiloVendido);
            ArrayList<Puesto>[] arrayListaPuestos = this.ventas.puestosPrecioMinimoyMaximo(
                    this.cantidadVendida[2], this.cantidadVendida[3], unProducto);
            this.puestoPrecioMaximo = arrayListaPuestos[1];
            this.puestosPrecioMinimo = arrayListaPuestos[0];
            this.mostrarListas();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        pnlPanel = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblTotalVendido = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTotalComprado = new javax.swing.JLabel();
        lblVentasPuestos = new javax.swing.JLabel();
        lblComprasPuestos = new javax.swing.JLabel();
        lblPrecioMinimo = new javax.swing.JLabel();
        lblPrecioMaximo = new javax.swing.JLabel();
        lblPuestosPrecioMinimo = new javax.swing.JLabel();
        lblPuestosPrecioMaximo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPrecioMinimo = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrecioMaximo = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblVenta = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtVenta = new javax.swing.JTextField();
        txtTotalVendido = new javax.swing.JTextField();
        txtTotalComprado = new javax.swing.JTextField();
        txtCantidadVendido = new javax.swing.JTextField();
        txtCantidadComprado = new javax.swing.JTextField();
        txtPrecioMaximo = new javax.swing.JTextField();
        txtPrecioMinimo = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtras.setText("<");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Información del producto");

        lblTotalVendido.setText("Total $ vendidio entre todos los puestos:");

        lblTotalComprado.setText("Total $ comprado por todos los puestos: ");

        lblVentasPuestos.setText("Cantidad total vendida entre todos los puestos (unidad/kilo):");

        lblComprasPuestos.setText("Cantidad total comprada entre todos los puestos (unidad/kilo):");

        lblPrecioMinimo.setText("Precio mínimo vendido");

        lblPrecioMaximo.setText("Precio máximo vendido:");

        lblPuestosPrecioMinimo.setText("Puestos con el precio de venta mínimo");

        lblPuestosPrecioMaximo.setText("Puestos con el precio de venta máximo");

        jScrollPane1.setViewportView(lstPrecioMinimo);

        jScrollPane2.setViewportView(lstPrecioMaximo);

        lblNombre.setText("Nombre:");

        lblDescripcion.setText("Descripción:");

        lblTipo.setText("Tipo:");

        lblVenta.setText("Venta por:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblDescripcion)
                    .addComponent(lblTipo)
                    .addComponent(lblVenta))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVenta)
                    .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        txtTotalComprado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCompradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPanelLayout = new javax.swing.GroupLayout(pnlPanel);
        pnlPanel.setLayout(pnlPanelLayout);
        pnlPanelLayout.setHorizontalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuestosPrecioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addComponent(lblPrecioMinimo)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPuestosPrecioMaximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addComponent(lblPrecioMaximo)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecioMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addComponent(lblVentasPuestos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotalVendido)
                            .addComponent(lblTotalComprado)
                            .addComponent(lblComprasPuestos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadComprado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalComprado, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pnlPanelLayout.setVerticalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPanelLayout.createSequentialGroup()
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalVendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalVendido))
                                .addGap(7, 7, 7)
                                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPanelLayout.createSequentialGroup()
                                        .addComponent(lblTotalComprado)
                                        .addGap(15, 15, 15)
                                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVentasPuestos)
                                            .addComponent(jLabel9)))
                                    .addGroup(pnlPanelLayout.createSequentialGroup()
                                        .addComponent(txtTotalComprado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCantidadVendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblComprasPuestos)
                                    .addComponent(txtCantidadComprado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrecioMinimo)
                                    .addComponent(lblPrecioMaximo)
                                    .addComponent(txtPrecioMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPuestosPrecioMinimo)
                                    .addComponent(lblPuestosPrecioMaximo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPanel);
        pnlPanel.setBounds(0, 0, 1020, 390);

        setBounds(0, 0, 1000, 397);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalCompradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCompradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCompradoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNombreActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDescripcionActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAtrasActionPerformed
        // Verifica que el usuario no pueda retorceder si esta en el primero
        if (this.indiceActual > 0) {
            this.indiceActual--;
            mostrarProducto();
        }
    }// GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSiguienteActionPerformed
        // Verifica que el usuario no pueda pasar a otro producto si esta en el ultimo
        int maximo = this.productos.getListaProductos().size();
        if (this.indiceActual < (maximo - 1)) {
            this.indiceActual++;
            mostrarProducto();
        }
    }// GEN-LAST:event_btnSiguienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblComprasPuestos;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioMaximo;
    private javax.swing.JLabel lblPrecioMinimo;
    private javax.swing.JLabel lblPuestosPrecioMaximo;
    private javax.swing.JLabel lblPuestosPrecioMinimo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTotalComprado;
    private javax.swing.JLabel lblTotalVendido;
    private javax.swing.JLabel lblVenta;
    private javax.swing.JLabel lblVentasPuestos;
    private javax.swing.JList lstPrecioMaximo;
    private javax.swing.JList lstPrecioMinimo;
    private javax.swing.JPanel pnlPanel;
    private javax.swing.JTextField txtCantidadComprado;
    private javax.swing.JTextField txtCantidadVendido;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioMaximo;
    private javax.swing.JTextField txtPrecioMinimo;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTotalComprado;
    private javax.swing.JTextField txtTotalVendido;
    private javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
    private RegistroCompra compras;
    private RegistroVenta ventas;
    private RegistroProducto productos;
    private HashMap<Producto, Integer> totalVendidos;
    private HashMap<Producto, Integer> totalCompras;
    private int[] cantidadComprada;
    private int[] cantidadVendida;
    private int precioMinimo;
    private int precioMaximo;
    private ArrayList<Puesto> puestosPrecioMinimo;
    private ArrayList<Puesto> puestoPrecioMaximo;
    private int indiceActual;
}
