/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaConsultas;

import Dominio.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Luciano Umpierrez 
 */
public class ConsultaDueño extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ConsultaDueño
     */
    public ConsultaDueño(RegistrarDueño unRegistroDueño) {
        initComponents();
        this.setTitle("Consulta dueño");
        this.registroDueño = unRegistroDueño;
        this.registroDueño.addObserver(this);
        //crearTablaDueños();
    }

    public void crearTablaDueños() {
        ArrayList<Dueño> dueños = registroDueño.getDueños();
        Collections.sort(dueños, Comparator.comparing(Dueño::getNombre, String.CASE_INSENSITIVE_ORDER));
        // Para poder pasar los datos a la tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaDueños.getModel();
        // para limpiarla
        modelo.setRowCount(0);
        for (Dueño dueño : dueños) {
            Object[] fila = {dueño.getNombre(), dueño.getEdad(), dueño.getAñosExp()};
            modelo.addRow(fila);
        }
    }
    @Override
    public void update(Observable o, Object arg){
        if(o instanceof RegistrarDueño && arg instanceof Dueño){
            crearTablaDueños();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelconsDueño = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDueños = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tablaDueños.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Años de experiencia"
            }
        ));
        jScrollPane2.setViewportView(tablaDueños);

        javax.swing.GroupLayout PanelconsDueñoLayout = new javax.swing.GroupLayout(PanelconsDueño);
        PanelconsDueño.setLayout(PanelconsDueñoLayout);
        PanelconsDueñoLayout.setHorizontalGroup(
            PanelconsDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelconsDueñoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelconsDueñoLayout.setVerticalGroup(
            PanelconsDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelconsDueñoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(PanelconsDueño);
        PanelconsDueño.setBounds(0, 0, 430, 300);

        setSize(new java.awt.Dimension(445, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelconsDueño;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaDueños;
    // End of variables declaration//GEN-END:variables
    private RegistrarDueño registroDueño;
}
