/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaMovimiento;

import Dominio.*;
import AreaRegistros.*;

/**
 *
 * @author Luciano Umpierrez
 */
public class AreaMovimiento extends javax.swing.JFrame {

    /**
     * Creates new form AreaMovimiento
     */
    public AreaMovimiento(RegistroPuesto unRegistroPuesto, RegistroMayorista unRegistroMayorista,
            RegistroCompra unRegistroCompra, RegistroVenta unRegistroVenta) {
        initComponents();
        this.setTitle("Área de movimientos");
        this.registroPuesto = unRegistroPuesto;
        this.registroMayorista = unRegistroMayorista;
        this.registroCompra = unRegistroCompra;
        this.registroVenta = unRegistroVenta;
        this.registrarVenta = new RegistrarVenta(registroCompra,
                registroPuesto, registroVenta);
        this.registrarCompra = new RegistrarCompra(registroMayorista,
                registroPuesto, registroCompra, unRegistroVenta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Registrar compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 90, 170, 23);

        jButton2.setText("Registrar venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 140, 170, 23);

        setSize(new java.awt.Dimension(415, 256));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        this.registrarCompra.objetoAPantalla();
        this.registrarCompra.setVisible(true);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.registrarVenta.setVisible(true);
        this.registrarVenta.objetosAPantalla();
    }// GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
    private RegistrarCompra registrarCompra;
    private RegistroMayorista registroMayorista;
    private RegistroPuesto registroPuesto;
    private RegistroCompra registroCompra;
    private RegistrarVenta registrarVenta;
    private RegistroVenta registroVenta;
}
