/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaMovimiento;

import Dominio.Producto;
import Dominio.Puesto;
import Dominio.RegistroCompra;
import Dominio.RegistroPuesto;
import Dominio.RegistroVenta;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

import AreaConsultas.GenerarArchivo;
import Dominio.Compra;

/**
 *
 * @author Luciano Umpierrez
 */
public class VentanaEmergenteVenta extends javax.swing.JFrame {
    private Compra compra;
    /**
     * Creates new form VentantaEmergenteVenta
     */
    public VentanaEmergenteVenta(RegistroVenta unRegistroVenta, RegistroCompra unRegistroCompra, 
            RegistroPuesto unRegistroPuesto) {
        initComponents();
        this.setTitle("Ingresar venta");
        this.ventas = unRegistroVenta;
        this.registroCompra = unRegistroCompra;
        this.registroPuesto = unRegistroPuesto;
        //this.generarArchivo = new GenerarArchivo(unRegistroCompra, unRegistroVenta, unRegistroPuesto);
    }

    public void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Eror",
                JOptionPane.ERROR_MESSAGE);
    }
    
    public void setCompra(Compra unaCompra){
        this.compra = unaCompra;
    }
    
    public void limpiarCampos(){
        this.txtCantidad.setText("");
        this.txtPrecio.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad");

        jLabel2.setText("Precio unitario");

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCantidad,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1))
                                                .addGap(64, 64, 64)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnComprar)
                                                .addGap(5, 5, 5)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(btnComprar)
                                .addContainerGap(43, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        setSize(new java.awt.Dimension(267, 170));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPrecioActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        try {
            int cuantoQuiere = Integer.parseInt(this.txtCantidad.getText());
            int precio = Integer.parseInt(this.txtPrecio.getText());
            int cantidadDisponible = this.compra.getCantidad();
            Producto producto = this.compra.getProducto();
            Puesto puesto = this.compra.getPuesto();
            if (cuantoQuiere <= cantidadDisponible) {
                int numero = this.ventas.registrarVenta(cuantoQuiere, precio,
                        producto, puesto);
                JOptionPane.showMessageDialog(null, "Venta exitosa. Recuerde gurdar su"
                        + " número de venta " + numero, "Felicidades",
                        JOptionPane.PLAIN_MESSAGE);
                this.registroCompra.reducirCantidadCompra(cuantoQuiere, producto, puesto);
                //this.generarArchivo.ObjetoaPantalla();
            } else {
                mensajeError("La cantidad disponible para compra es de "
                        + cantidadDisponible);
            }
        } catch (InputMismatchException e) {
            mensajeError("Debe ingresar precio y cantidad en formato numerico");
        }
        this.limpiarCampos();
    }// GEN-LAST:event_btnComprarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCantidadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
    private RegistroVenta ventas;
    //private GenerarArchivo generarArchivo;
    private RegistroCompra registroCompra;
    private RegistroPuesto registroPuesto;
}
