/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaRegistros;

import Dominio.RegistrarDueño;
import Dominio.RegistroMayorista;
import Dominio.RegistroProducto;
import Dominio.RegistroPuesto;

/**
 *
 * @author Luciano Umpierrez
 */
public class AreaRegistros extends javax.swing.JFrame {

    /**
     * Creates new form AreaRegistros
     */
    public AreaRegistros(RegistroMayorista unRegistroMayorista, RegistrarDueño unRegistroDueño, RegistroPuesto unRegistroPuesto, RegistroProducto unRegistroProducto){
        initComponents();
        this.setTitle("Área de registros");
        this.registroD = unRegistroDueño;
        this.registroPue = unRegistroPuesto;
        this.registroMayo = unRegistroMayorista;
        this.registroProduc = unRegistroProducto;
        this.registrarProducto = new RegistrarProducto(registroProduc);
        this.registrarMayorista = new RegistrarMayorista(registroMayo, registroProduc);
        this.registrarPuesto = new RegistrarPuesto(registroPue, registroD);
        this.registrarDueñoPuesto = new RegistroDueñoPuesto(registroD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrarProducto = new javax.swing.JButton();
        btnRegistrarDueño = new javax.swing.JButton();
        btnRegistrarPuesto = new javax.swing.JButton();
        btnRegistrarMayorista = new javax.swing.JButton();
        lblQueHacer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnRegistrarProducto.setText("Registrar producto");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        btnRegistrarDueño.setText("Registrar dueño");
        btnRegistrarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDueñoActionPerformed(evt);
            }
        });

        btnRegistrarPuesto.setText("Registrar puesto");
        btnRegistrarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPuestoActionPerformed(evt);
            }
        });

        btnRegistrarMayorista.setText("Registrar mayorista");
        btnRegistrarMayorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMayoristaActionPerformed(evt);
            }
        });

        lblQueHacer.setText("¿Que desea hacer?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarDueño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarMayorista, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblQueHacer)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblQueHacer)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarProducto)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarDueño)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarPuesto)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarMayorista)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 260);

        setSize(new java.awt.Dimension(406, 270));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPuestoActionPerformed
        this.registrarPuesto.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPuestoActionPerformed

    private void btnRegistrarMayoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMayoristaActionPerformed
        this.registrarMayorista.ObjetosPantalla();
        this.registrarMayorista.setVisible(true);
    }//GEN-LAST:event_btnRegistrarMayoristaActionPerformed

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        this.registrarProducto.setVisible(true);
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    private void btnRegistrarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDueñoActionPerformed
        // TODO add your handling code here:
        this.registrarDueñoPuesto.setVisible(true);
    }//GEN-LAST:event_btnRegistrarDueñoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarDueño;
    private javax.swing.JButton btnRegistrarMayorista;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JButton btnRegistrarPuesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQueHacer;
    // End of variables declaration//GEN-END:variables
    private RegistrarPuesto registrarPuesto;
    private RegistrarMayorista registrarMayorista;
    private RegistrarProducto registrarProducto;
    private RegistroDueñoPuesto registrarDueñoPuesto;
    private RegistrarDueño registroD; 
    private RegistroPuesto registroPue;
    private RegistroMayorista registroMayo;
    private RegistroProducto registroProduc;
}
