/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaRegistros;

import Dominio.Dueño;
import Dominio.Puesto;
import Dominio.RegistroPuesto;
import Dominio.RegistrarDueño;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Luciano Umpierrez
 */
public class RegistrarPuesto extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPuesto
     */
    public RegistrarPuesto(RegistroPuesto unRegistroPuesto, RegistrarDueño unRegistroDueño) {
        initComponents();
        this.setTitle("Registrar puesto");
        this.registro = unRegistroPuesto;
        this.registroDueños = unRegistroDueño;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtfID = new javax.swing.JTextField();
        lblDueño = new javax.swing.JLabel();
        txtfDueño = new javax.swing.JTextField();
        lblUbi = new javax.swing.JLabel();
        txtfUbi = new javax.swing.JTextField();
        lblCantEmpleados = new javax.swing.JLabel();
        txtfCantEmpleados = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("RegistrarPuesto"); // NOI18N
        getContentPane().setLayout(null);

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblID.setText("Identificación:");

        txtfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfIDActionPerformed(evt);
            }
        });

        lblDueño.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDueño.setText("Dueño:");

        txtfDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDueñoActionPerformed(evt);
            }
        });

        lblUbi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUbi.setText("Ubicación:");

        txtfUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfUbiActionPerformed(evt);
            }
        });

        lblCantEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCantEmpleados.setText("Cantidad de empleados:");

        txtfCantEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCantEmpleadosActionPerformed(evt);
            }
        });

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAlta)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUbi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantEmpleados))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfDueño, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtfID, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtfUbi, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtfCantEmpleados))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDueño))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUbi)
                    .addComponent(txtfUbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantEmpleados)
                    .addComponent(txtfCantEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnAlta)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 270);

        setSize(new java.awt.Dimension(391, 301));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfIDActionPerformed

    private void txtfDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDueñoActionPerformed

    private void txtfUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfUbiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfUbiActionPerformed

    private void txtfCantEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCantEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCantEmpleadosActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        try {
            if(this.txtfID.getText().equals("") || this.txtfDueño.getText().equals("") ||
                    this.txtfCantEmpleados.getText().equals("") ||
                    this.txtfUbi.getText().equals("")){
            
                throw new Exception("Deben estar todos los campos completos");
            }
            
            if (registro.existeID(this.txtfID.getText())) {
                throw new Exception("Esa identificacion ya pertenece a un puesto.");
            }
            
            String identificacion = this.txtfID.getText();
            if (registroDueños.existeDueño(this.txtfDueño.getText())) {
                String nombreDueño = this.txtfDueño.getText();
                Dueño dueño = registroDueños.retornarDueño(nombreDueño);
                String ubi = this.txtfUbi.getText();
                int cantEmpleados = Integer.parseInt(this.txtfCantEmpleados.getText());
                registro.RegistrarPuesto(identificacion, dueño, ubi, cantEmpleados);
                JOptionPane.showMessageDialog(this,
                        "Su puesto ha sido ingresado correctamente.",
                        "Ingreso exitoso", JOptionPane.INFORMATION_MESSAGE);
                this.txtfDueño.setText("");
                this.txtfID.setText("");
                this.txtfUbi.setText("");
                this.txtfCantEmpleados.setText("");
            } else {
                throw new Exception("No existe ese dueño.");
            }
        }catch(NumberFormatException e){
            String error = "Cantidad de empleados debe ser ingresada en formato numerico.";
            mostrarError(error);  
        } catch (Exception e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantEmpleados;
    private javax.swing.JLabel lblDueño;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblUbi;
    private javax.swing.JTextField txtfCantEmpleados;
    private javax.swing.JTextField txtfDueño;
    private javax.swing.JTextField txtfID;
    private javax.swing.JTextField txtfUbi;
    // End of variables declaration//GEN-END:variables
    private RegistroPuesto registro;
    private ArrayList<Puesto> listaPuestos;
    private RegistrarDueño registroDueños;
}
