/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaRegistros;

import Dominio.*;
import java.awt.HeadlessException;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import java.util.Observer;
import java.util.Observable;

/**
 *
 * @author Luciano Umpierrez
 */
public class RegistrarMayorista extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form RegistrarMayorista
     */
    public RegistrarMayorista(RegistroMayorista unRegistro, RegistroProducto unProductoDisponible) {
        initComponents();
        this.setTitle("Registrar mayorista");
        this.registroMayoristas = unRegistro;
        this.productosDisponibles = unProductoDisponible;
        this.listaProductosSeleccionados = new ArrayList<>();
        unProductoDisponible.agregarObservador(this);
        ObjetosPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMayorista = new javax.swing.JPanel();
        lblRUT = new javax.swing.JLabel();
        txtfRUT = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtfNombre = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtfDireccion = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProductosAdd = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        btnAlta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnQuitarProducto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listProductos = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblRUT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRUT.setText("RUT:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDireccion.setText("Dirección: ");

        lblProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProducto.setText("Producto:");

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseEntered(evt);
            }
        });
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listProductosAdd);

        javax.swing.GroupLayout PanelMayoristaLayout = new javax.swing.GroupLayout(PanelMayorista);
        PanelMayorista.setLayout(PanelMayoristaLayout);
        PanelMayoristaLayout.setHorizontalGroup(
            PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMayoristaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion)
                    .addComponent(lblProducto)
                    .addComponent(lblNombre)
                    .addComponent(lblRUT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMayoristaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfRUT, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarProducto))
                        .addGap(350, 350, 350))
                    .addGroup(PanelMayoristaLayout.createSequentialGroup()
                        .addGroup(PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelMayoristaLayout.setVerticalGroup(
            PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMayoristaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRUT)
                    .addComponent(txtfRUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMayoristaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMayoristaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDireccion)))
                .addGap(28, 28, 28)
                .addGroup(PanelMayoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelMayoristaLayout.createSequentialGroup()
                        .addComponent(lblProducto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelMayoristaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarProducto)
                        .addGap(20, 20, 20))))
        );

        getContentPane().add(PanelMayorista);
        PanelMayorista.setBounds(0, 0, 390, 380);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Productos agregados:");

        btnQuitarProducto.setText("Eliminar");
        btnQuitarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarProductoActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(listProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnQuitarProducto)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuitarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnAlta)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(390, 0, 340, 360);

        setSize(new java.awt.Dimension(742, 401));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void ObjetosPantalla() {
        Producto[] arrProductos = this.productosDisponibles.getListaProductos().toArray(
                new Producto[this.productosDisponibles.getListaProductos().size()]);
        this.listProductosAdd.setListData(arrProductos);
    }

    @Override
    public void update(Observable observado, Object arg) {
        if (arg instanceof Producto) {
            ObjetosPantalla();
        }
    }

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarProductoActionPerformed
        try {
            Producto seleccion = (Producto) listProductosAdd.getSelectedValue();
            if (seleccion != null && !this.listaProductosSeleccionados.contains(seleccion)) {
                this.listaProductosSeleccionados.add(seleccion);
                Producto[] arrayProductos = this.listaProductosSeleccionados.toArray(
                        new Producto[this.listaProductosSeleccionados.size()]);
                this.listProductos.setListData(arrayProductos);
            } else {
                throw new Exception("Producto ya agregado");
            }
        } catch (Exception e) {
            this.mostrarError(e.getMessage());
        }

    }// GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAltaActionPerformed
        // registroMayoristas = new RegistroMayorista();
        try {

            if (this.txtfRUT.getText().equals("") || this.txtfNombre.getText().equals("")
                    || this.txtfDireccion.getText().equals("")) {

                throw new Exception("Debe completar todos los datos");
            }
            if (registroMayoristas.validarRut(this.txtfRUT.getText())) {
                if (!registroMayoristas.existeRut(this.txtfRUT.getText())) {
                    String rut = this.txtfRUT.getText();
                    String nombre = this.txtfNombre.getText();
                    String direccion = this.txtfDireccion.getText();
                    if (!this.listaProductosSeleccionados.isEmpty()) {
                        registroMayoristas.RegistrarMayorista(rut, nombre, direccion,
                                listaProductosSeleccionados);
                        JOptionPane.showMessageDialog(this,
                                "Mayorista ingresado correctamente",
                                "Exito", JOptionPane.INFORMATION_MESSAGE);
                        this.txtfRUT.setText("");
                        this.txtfNombre.setText("");
                        this.txtfDireccion.setText("");
                        Producto[] arrayVacio = new Producto[1];
                        this.listProductos.setListData(arrayVacio);
                        this.listaProductosSeleccionados = new ArrayList<>();
                    } else {
                        mostrarError("Error: debe al menos ingresar un producto");
                    }
                } else {
                    mostrarError("Error: ese RUT ya pertenece a un mayorista.");
                }
            } else {
                mostrarError(
                        "Error: Rut invalido, debe ingresar 8 digitos numericos y un digito verificador alfanumerico separado de un caracter especial");
            }
        } catch (Exception e) {
            mostrarError(e.getMessage());
        }
    }// GEN-LAST:event_btnAltaActionPerformed

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void btnQuitarProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnQuitarProductoActionPerformed
        try {
            Producto seleccion = (Producto) listProductos.getSelectedValue();
            if (seleccion != null) {
                this.listaProductosSeleccionados.remove(seleccion);
                Producto[] arrayProductos = this.listaProductosSeleccionados.toArray(
                        new Producto[this.listaProductosSeleccionados.size()]);
                this.listProductos.setListData(arrayProductos);
            } else {
                throw new Exception("Debe seleccinar un producto");
            }
        } catch (Exception e) {
            mostrarError(e.getMessage());
        }
    }// GEN-LAST:event_btnQuitarProductoActionPerformed

    private void btnAgregarProductoMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnAgregarProductoMouseEntered

    }// GEN-LAST:event_btnAgregarProductoMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMayorista;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnQuitarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblRUT;
    private javax.swing.JList listProductos;
    private javax.swing.JList listProductosAdd;
    private javax.swing.JTextField txtfDireccion;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfRUT;
    // End of variables declaration//GEN-END:variables
    // private AreaRegistros areaRegistros;
    private RegistroMayorista registroMayoristas;
    private ArrayList<Producto> listaProductosSeleccionados;
    private RegistroProducto productosDisponibles;
}
