package AreaRegistros;

import javax.swing.JOptionPane;
import Dominio.RegistrarDueño;

/**
 *
 * @author Luciano Umpierrez
 */
public class RegistroDueñoPuesto extends javax.swing.JFrame {

    /**
     * Creates new form RegistroDueñoPuesto
     */
    public RegistroDueñoPuesto(RegistrarDueño unRegistro) {
        initComponents();
        this.setTitle("Registrar dueño");
        this.registro = unRegistro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textNombre = new javax.swing.JTextField();
        textEdad = new javax.swing.JTextField();
        textExperiencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        textEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEdadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Edad");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Años de experiencia");

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnAlta)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                .addGap(59, 59, 59)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                123, Short.MAX_VALUE)
                                                        .addComponent(textEdad)
                                                        .addComponent(textExperiencia))))
                                .addContainerGap(45, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(textExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59,
                                        Short.MAX_VALUE)
                                .addComponent(btnAlta)
                                .addGap(40, 40, 40)));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 380, 300);

        setSize(new java.awt.Dimension(412, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textEdadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textEdadActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textEdadActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
        String nombre = this.textNombre.getText();
        int años = 0;
        int exp = 0;
        boolean exitoso = false;

        try {
            if (nombre.equals("") || textEdad.getText().equals("") ||
                    textExperiencia.getText().equals("")) {
                throw new Exception("Todos los campos deben estar completos.");
            }
            if (Integer.parseInt(this.textEdad.getText()) > 100) {
                throw new Exception("Ingrese una edad menor o igual a 100");
            }
            if (Integer.parseInt(this.textExperiencia.getText()) >= Integer.parseInt(this.textEdad.getText())) {
                throw new Exception("No puedes tener la misma o mas años de experiencia que la edad que tienes");
            }
            años = Integer.parseInt(this.textEdad.getText());
            exp = Integer.parseInt(this.textExperiencia.getText());
            exitoso = registro.registrarDueños(exp, nombre, años);

            if (!exitoso) {
                // mostrar ventana dando error con mensaje de esta repetido
                JOptionPane.showMessageDialog(this,
                        "Nombre repetido, ingrese un nombre valido.",
                        "Error al insertar", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Su dueño de puesto ha sido ingresado correctamente.",
                        "Ingreso exitoso", JOptionPane.INFORMATION_MESSAGE);
                this.textNombre.setText("");
                this.textEdad.setText("");
                this.textExperiencia.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Edad y años de experiencia deben ser ingresados en formato numerico.",
                    "Error al insertar", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Error al insertar", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnAltaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textEdad;
    private javax.swing.JTextField textExperiencia;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
    private RegistrarDueño registro;
}
