/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AreaRegistros;

import java.awt.Image;
import java.io.File;
import java.util.*;
import javax.swing.*;
import Dominio.RegistroProducto;

/**
 *
 * @author Luciano Umpierrez
 */
public class RegistrarProducto extends javax.swing.JFrame {

    /**
     * Creates new form AreaRegistro
     */
    public RegistrarProducto(RegistroProducto unRegistro) {
        Locale.setDefault(new Locale("es", "ES"));
        initComponents();
        this.setTitle("Registrar producto");
        this.sinImagen = "./sinImagen.png";
        ImageIcon imageIcon = new ImageIcon(this.sinImagen);
        this.lblImagen.setIcon(imageIcon);
        registro = unRegistro;
        cambiarIdiomaFileChooser(this.fcImagenes);
        fcImagenes.setCurrentDirectory(new File("ImagenesOblig")); // Establecer directorio inicial del JFileChooser
    }

    private static void cambiarIdiomaFileChooser(JFileChooser fileChooser) {
        UIManager.put("FileChooser.openDialogTitleText", "Abrir archivo");
        UIManager.put("FileChooser.saveDialogTitleText", "Guardar archivo");
        UIManager.put("FileChooser.lookInLabelText", "Buscar en:");
        UIManager.put("FileChooser.saveInLabelText", "Guardar en:");
        UIManager.put("FileChooser.openButtonText", "Abrir");
        UIManager.put("FileChooser.saveButtonText", "Guardar");
        UIManager.put("FileChooser.cancelButtonText", "Cancelar");
        UIManager.put("FileChooser.fileNameLabelText", "Nombre de archivo:");
        UIManager.put("FileChooser.filesOfTypeLabelText", "Tipo de archivos:");
        UIManager.put("FileChooser.folderNameLabelText", "Directorio:");
        SwingUtilities.updateComponentTreeUI(fileChooser);
    }

    public void reset() {
        this.txtfNombre.setText("");
        this.txtfDescripcion.setText("");
        this.fcImagenes.setSelectedFile(null);
        this.lblImagen.setIcon(null);
        ImageIcon imageIcon = new ImageIcon(this.sinImagen);
        this.lblImagen.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtfNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtfDescripcion = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cboxTipo = new javax.swing.JComboBox<>();
        lblVentaPor = new javax.swing.JLabel();
        cboxMagnitud = new javax.swing.JComboBox<>();
        fcImagenes = new javax.swing.JFileChooser();
        lblElegirImagen = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripción:");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setText("Tipo:");

        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruta", "Verdura" }));

        lblVentaPor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVentaPor.setText("Venta por:");

        cboxMagnitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogramo", "Unidad" }));

        fcImagenes.setCurrentDirectory(new java.io.File("C:\\Users\\umpi1\\Downloads\\Obligatorio2-20230519T170942Z-001\\Obligatorio2\\ImagenesOblig"));
        fcImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcImagenesActionPerformed(evt);
            }
        });

        lblElegirImagen.setText("Imagenes");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescripcion)
                                    .addComponent(lblNombre)
                                    .addComponent(lblTipo)
                                    .addComponent(lblVentaPor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboxMagnitud, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtfDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(txtfNombre)))
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, Short.MAX_VALUE)
                        .addComponent(fcImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblElegirImagen)
                .addGap(319, 319, 319))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblElegirImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcion)
                            .addComponent(txtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(cboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxMagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVentaPor))
                        .addGap(24, 24, 24)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset)
                            .addComponent(btnAlta))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fcImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 102, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 450);

        setSize(new java.awt.Dimension(839, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fcImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcImagenesActionPerformed
        if (!evt.getActionCommand().equals(JFileChooser.CANCEL_SELECTION)) {
            File selectedFile = fcImagenes.getSelectedFile();
            String imagePath = selectedFile.getAbsolutePath();

            ImageIcon imageIcon = new ImageIcon(imagePath);
            this.lblImagen.setIcon(imageIcon);
        } else {
            ImageIcon imageIcon = new ImageIcon(this.sinImagen); // Ruta relativa
            this.lblImagen.setIcon(imageIcon);
        }

    }//GEN-LAST:event_fcImagenesActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
        try {
            File selectedFile = fcImagenes.getSelectedFile();
            if (this.txtfNombre.getText().equals("") || this.txtfDescripcion.getText().equals("")
                    || this.lblImagen.getIcon().equals(this.sinImagen) || selectedFile == null) {

                throw new Exception("Todos los campos deben estar completos");
            } else {
                if (this.txtfNombre.getText().contains(".")) {
                    throw new Exception("Los nombres no pueden contener puntos");
                }
                if (this.registro.productoYaRegistrado(this.txtfNombre.getText())) {
                    throw new Exception("Ese producto ya fue registrado");
                } else {
                    String nombre = this.txtfNombre.getText();
                    String descripcion = this.txtfDescripcion.getText();
                    String tipo = (String) this.cboxTipo.getSelectedItem();
                    String formaDeVenta = (String) this.cboxMagnitud.getSelectedItem();
                    String foto = selectedFile.getAbsolutePath();

                    registro.registrarProducto(nombre, descripcion,
                            tipo, formaDeVenta, foto);

                    JOptionPane.showMessageDialog(this,
                            "Producto ingresado correctamente",
                            "Error", JOptionPane.INFORMATION_MESSAGE);
                    this.reset();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnAltaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cboxMagnitud;
    private javax.swing.JComboBox<String> cboxTipo;
    private javax.swing.JFileChooser fcImagenes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblElegirImagen;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblVentaPor;
    private javax.swing.JTextField txtfDescripcion;
    private javax.swing.JTextField txtfNombre;
    // End of variables declaration//GEN-END:variables
    String sinImagen;
    private RegistroProducto registro;
    private AreaRegistros areaRegistro;
}
